import { Router } from 'express';
import type { NodeCatalogEntry } from 'orchestream-ai-shared';
import { asyncHandler } from '../utils/async-handler.js';

const router = Router();

export const catalog: NodeCatalogEntry[] = [
  {
    type: 'llm-agent',
    label: 'LLM Agent',
    category: 'processing',
    description: 'Call an LLM with a system prompt. Select from centrally managed endpoints.',
    defaultConfig: { endpointId: '', model: '', systemPrompt: '', responseFormat: 'text', outputSchema: '', thinkingMode: 'default' },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'mcp-tool',
    label: 'MCP Tool',
    category: 'tools',
    description: 'Call a tool on a centrally configured MCP server',
    defaultConfig: { serverId: '', toolName: '', parameters: {} },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'flow-tool',
    label: 'Flow Tool',
    category: 'tools',
    description: 'Expose webhook flows as tools for LLM Agents. Select multiple flows — each becomes a callable tool.',
    defaultConfig: { flowIds: [], selectedFlows: [] },
    inputs: 0,
    outputs: 0,
  },
  {
    type: 'retriever',
    label: 'Retriever',
    category: 'tools',
    description: 'Query a vector store for relevant documents using semantic search',
    defaultConfig: { embeddingProviderId: '', vectorStoreId: '', collectionName: '', topK: 5, minScore: 0.7 },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'condition',
    label: 'Condition',
    category: 'processing',
    description: 'Route execution based on a boolean condition. Always creates true/false paths.',
    defaultConfig: { condition: '' },
    inputs: 1,
    outputs: 2,
  },
  {
    type: 'switch',
    label: 'Switch',
    category: 'processing',
    description: 'Route execution based on the value of a selected input field. Each case becomes a separate output path.',
    defaultConfig: { fieldPath: '', cases: [] },
    inputs: 1,
    outputs: 0,
  },
  {
    type: 'code',
    label: 'Code',
    category: 'processing',
    description: 'Run custom JavaScript code to transform data between nodes',
    defaultConfig: { language: 'javascript', code: '// Transform the input payload\nreturn payload;' },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'parallel',
    label: 'Parallel Agents',
    category: 'processing',
    description: 'Run multiple LLM Agent nodes concurrently. Each receives the same input, and their outputs are merged.',
    defaultConfig: { subNodes: [], subEdges: [] },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'subflow',
    label: 'Subflow',
    category: 'processing',
    description: 'Execute another flow as a sub-routine. Pass input parameters and receive structured output.',
    defaultConfig: { subflowId: '', inputMapping: {} },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'hitl',
    label: 'Human in the Loop',
    category: 'processing',
    description: 'Pause the flow for human approval. Shows upstream output and waits for approve/reject.',
    defaultConfig: { prompt: 'Please review the following before continuing:', buttons: [{ label: 'Approve', value: 'approved' }, { label: 'Reject', value: 'rejected' }], allowFeedback: true },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'http',
    label: 'HTTP Request',
    category: 'tools',
    description: 'Make HTTP requests to external APIs with support for method, URL, headers, body, and authentication.',
    defaultConfig: { method: 'GET', url: '', headers: '', body: '', authType: 'none', followRedirects: true, timeout: 30000, retries: 0, sslVerify: true },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'loop',
    label: 'Loop',
    category: 'processing',
    description: 'Iterate over an array of items and execute a sub-graph for each item sequentially. Use a Parallel node inside the loop for concurrent execution.',
    defaultConfig: { itemsField: '', itemVariable: 'item', indexVariable: 'index', subNodes: [], subEdges: [], collectResults: true },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'delay',
    label: 'Delay',
    category: 'processing',
    description: 'Pause execution for a fixed duration, ISO 8601 duration, or until a specific timestamp.',
    defaultConfig: { type: 'fixed', seconds: 5 },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'ai-action',
    label: 'AI Action',
    category: 'processing',
    description: 'A lightweight single LLM call for text transformation (summarize, classify, extract, translate). No tool loop, no context layering.',
    defaultConfig: { endpointId: '', model: '', prompt: '', temperature: 0.7, maxTokens: 1024, responseFormat: 'text', thinkingMode: 'default' },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'map',
    label: 'Map',
    category: 'processing',
    description: 'Build a JSON object by mapping upstream fields to output fields. Generates a schema so downstream nodes see the exact output shape.',
    defaultConfig: { fields: [], mode: 'replace' },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'note',
    label: 'Note',
    category: 'processing',
    description: 'A visual annotation on the canvas for documentation purposes. Has no execution behavior.',
    defaultConfig: { content: '' },
    inputs: 0,
    outputs: 0,
  },
  {
    type: 'output',
    label: 'Output',
    category: 'output',
    description: 'Final output of the flow. Returns selected field(s) as text or JSON.',
    defaultConfig: {},
    inputs: 1,
    outputs: 0,
  },
];

router.get(
  '/',
  asyncHandler(async (_req, res) => {
    res.json(catalog);
  }),
);

export default router;
